export const LOG_IN =  'LOG_IN'
export const LOG_OUT =  'LOG_OUT'
export const REQUEST_USER = 'REQUEST_USER'
export const RECEIVE_USER = 'RECEIVE_USER'
export const FILTER_CARDS = 'FILTER_CARDS'
export const UNFILTER_CARDS = 'UNFILTER_CARDS'
